  name: Build and deploy ASP.Net Core app to Azure Web App - wa-bodymetrics
  
  on:
    push:
      branches:
        - main
    workflow_dispatch:
  
  jobs:
    build:
      runs-on: windows-latest
      
      permissions:
        contents: read
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup .NET 10
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '10.0.x'

        - name: Restore dependencies
          run: dotnet restore ./src/BodyMetricsApi.slnx

        - name: Build
          run: dotnet build ./src/BodyMetricsApi.slnx --configuration Release --no-restore

        - name: Publish application
          run: dotnet publish ./src/BodyMetricsApi/BodyMetricsApi.csproj -c Release --no-build -o ./publish

        - name: Upload published artifact
          uses: actions/upload-artifact@v4
          with:
            name: published-app
            path: ./publish
    
    deploy:
      runs-on: windows-latest
      needs: build
      
      permissions:
        id-token: write
        contents: read
      
      steps:
        - name: Download published artifact
          uses: actions/download-artifact@v4
          with:
            name: published-app
            path: ./publish

        - name: Azure Login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_683385E49BC4427C9BB503DDB7D99F47 }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2E3EA1C840A4407A8A5D9743D3BF1012 }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ABE4E918A9C043B5AD4D1698D182A3B4 }}

        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v3
          with:
            app-name: 'wa-bodymetrics'
            package: ./publish